// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: primenumber/protocolbuffer/primenumber.proto

package protocolbuffer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimeNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PrimeNumber) Reset() {
	*x = PrimeNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primenumber_protocolbuffer_primenumber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumber) ProtoMessage() {}

func (x *PrimeNumber) ProtoReflect() protoreflect.Message {
	mi := &file_primenumber_protocolbuffer_primenumber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumber.ProtoReflect.Descriptor instead.
func (*PrimeNumber) Descriptor() ([]byte, []int) {
	return file_primenumber_protocolbuffer_primenumber_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeNumber) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimeNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimeNumber *PrimeNumber `protobuf:"bytes,1,opt,name=primeNumber,proto3" json:"primeNumber,omitempty"`
}

func (x *PrimeNumberRequest) Reset() {
	*x = PrimeNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primenumber_protocolbuffer_primenumber_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumberRequest) ProtoMessage() {}

func (x *PrimeNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_primenumber_protocolbuffer_primenumber_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumberRequest.ProtoReflect.Descriptor instead.
func (*PrimeNumberRequest) Descriptor() ([]byte, []int) {
	return file_primenumber_protocolbuffer_primenumber_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeNumberRequest) GetPrimeNumber() *PrimeNumber {
	if x != nil {
		return x.PrimeNumber
	}
	return nil
}

type PrimeNumberManyTimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PrimeNumberManyTimesResponse) Reset() {
	*x = PrimeNumberManyTimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primenumber_protocolbuffer_primenumber_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeNumberManyTimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeNumberManyTimesResponse) ProtoMessage() {}

func (x *PrimeNumberManyTimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_primenumber_protocolbuffer_primenumber_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeNumberManyTimesResponse.ProtoReflect.Descriptor instead.
func (*PrimeNumberManyTimesResponse) Descriptor() ([]byte, []int) {
	return file_primenumber_protocolbuffer_primenumber_proto_rawDescGZIP(), []int{2}
}

func (x *PrimeNumberManyTimesResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_primenumber_protocolbuffer_primenumber_proto protoreflect.FileDescriptor

var file_primenumber_protocolbuffer_primenumber_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x25,
	0x0a, 0x0b, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0b, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x1c, 0x50, 0x72,
	0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0x86, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x70, 0x0a, 0x18, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_primenumber_protocolbuffer_primenumber_proto_rawDescOnce sync.Once
	file_primenumber_protocolbuffer_primenumber_proto_rawDescData = file_primenumber_protocolbuffer_primenumber_proto_rawDesc
)

func file_primenumber_protocolbuffer_primenumber_proto_rawDescGZIP() []byte {
	file_primenumber_protocolbuffer_primenumber_proto_rawDescOnce.Do(func() {
		file_primenumber_protocolbuffer_primenumber_proto_rawDescData = protoimpl.X.CompressGZIP(file_primenumber_protocolbuffer_primenumber_proto_rawDescData)
	})
	return file_primenumber_protocolbuffer_primenumber_proto_rawDescData
}

var file_primenumber_protocolbuffer_primenumber_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_primenumber_protocolbuffer_primenumber_proto_goTypes = []interface{}{
	(*PrimeNumber)(nil),                  // 0: protocolbuffer.PrimeNumber
	(*PrimeNumberRequest)(nil),           // 1: protocolbuffer.PrimeNumberRequest
	(*PrimeNumberManyTimesResponse)(nil), // 2: protocolbuffer.PrimeNumberManyTimesResponse
}
var file_primenumber_protocolbuffer_primenumber_proto_depIdxs = []int32{
	0, // 0: protocolbuffer.PrimeNumberRequest.primeNumber:type_name -> protocolbuffer.PrimeNumber
	1, // 1: protocolbuffer.PrimeNumberService.PrimeNumberDeComposition:input_type -> protocolbuffer.PrimeNumberRequest
	2, // 2: protocolbuffer.PrimeNumberService.PrimeNumberDeComposition:output_type -> protocolbuffer.PrimeNumberManyTimesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_primenumber_protocolbuffer_primenumber_proto_init() }
func file_primenumber_protocolbuffer_primenumber_proto_init() {
	if File_primenumber_protocolbuffer_primenumber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_primenumber_protocolbuffer_primenumber_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primenumber_protocolbuffer_primenumber_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primenumber_protocolbuffer_primenumber_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeNumberManyTimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_primenumber_protocolbuffer_primenumber_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_primenumber_protocolbuffer_primenumber_proto_goTypes,
		DependencyIndexes: file_primenumber_protocolbuffer_primenumber_proto_depIdxs,
		MessageInfos:      file_primenumber_protocolbuffer_primenumber_proto_msgTypes,
	}.Build()
	File_primenumber_protocolbuffer_primenumber_proto = out.File
	file_primenumber_protocolbuffer_primenumber_proto_rawDesc = nil
	file_primenumber_protocolbuffer_primenumber_proto_goTypes = nil
	file_primenumber_protocolbuffer_primenumber_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeNumberServiceClient is the client API for PrimeNumberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeNumberServiceClient interface {
	//Server Streaming
	PrimeNumberDeComposition(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (PrimeNumberService_PrimeNumberDeCompositionClient, error)
}

type primeNumberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeNumberServiceClient(cc grpc.ClientConnInterface) PrimeNumberServiceClient {
	return &primeNumberServiceClient{cc}
}

func (c *primeNumberServiceClient) PrimeNumberDeComposition(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (PrimeNumberService_PrimeNumberDeCompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeNumberService_serviceDesc.Streams[0], "/protocolbuffer.PrimeNumberService/PrimeNumberDeComposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeNumberServicePrimeNumberDeCompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeNumberService_PrimeNumberDeCompositionClient interface {
	Recv() (*PrimeNumberManyTimesResponse, error)
	grpc.ClientStream
}

type primeNumberServicePrimeNumberDeCompositionClient struct {
	grpc.ClientStream
}

func (x *primeNumberServicePrimeNumberDeCompositionClient) Recv() (*PrimeNumberManyTimesResponse, error) {
	m := new(PrimeNumberManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeNumberServiceServer is the server API for PrimeNumberService service.
type PrimeNumberServiceServer interface {
	//Server Streaming
	PrimeNumberDeComposition(*PrimeNumberRequest, PrimeNumberService_PrimeNumberDeCompositionServer) error
}

// UnimplementedPrimeNumberServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeNumberServiceServer struct {
}

func (*UnimplementedPrimeNumberServiceServer) PrimeNumberDeComposition(*PrimeNumberRequest, PrimeNumberService_PrimeNumberDeCompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDeComposition not implemented")
}

func RegisterPrimeNumberServiceServer(s *grpc.Server, srv PrimeNumberServiceServer) {
	s.RegisterService(&_PrimeNumberService_serviceDesc, srv)
}

func _PrimeNumberService_PrimeNumberDeComposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeNumberServiceServer).PrimeNumberDeComposition(m, &primeNumberServicePrimeNumberDeCompositionServer{stream})
}

type PrimeNumberService_PrimeNumberDeCompositionServer interface {
	Send(*PrimeNumberManyTimesResponse) error
	grpc.ServerStream
}

type primeNumberServicePrimeNumberDeCompositionServer struct {
	grpc.ServerStream
}

func (x *primeNumberServicePrimeNumberDeCompositionServer) Send(m *PrimeNumberManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeNumberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocolbuffer.PrimeNumberService",
	HandlerType: (*PrimeNumberServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDeComposition",
			Handler:       _PrimeNumberService_PrimeNumberDeComposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primenumber/protocolbuffer/primenumber.proto",
}
